# Generated by Django 5.0.1 on 2024-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divorce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband', models.CharField(max_length=100)),
                ('wife', models.CharField(max_length=100)),
                ('divorce_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.CharField(max_length=100)),
                ('bride', models.CharField(max_length=100)),
                ('marriage_date', models.DateField()),
            ],
        ),
    ]
